### ISSUE TITLE
transient install error

### ISSUE THREAD

**Issue by mattsb42** [mattsb42/accretion#22]
Encountered a transient install error.
It looks like this is `pip install --upgrade pip` breaking for some reason??

```
[DEBUG]	2019-06-17T01:59:42.362Z	011d47bd-3265-4b59-a8dc-be3d7515a9b3	Exception:
Traceback (most recent call last):
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 331, in _error_catcher
yield
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 413, in read
data = self._fp.read(amt)
File "/var/lang/lib/python3.6/http/client.py", line 449, in read
n = self.readinto(b)
File "/var/lang/lib/python3.6/http/client.py", line 493, in readinto
n = self.fp.readinto(b)
File "/var/lang/lib/python3.6/socket.py", line 586, in readinto
return self._sock.recv_into(b)
File "/var/lang/lib/python3.6/ssl.py", line 1012, in recv_into
return self.read(nbytes, buffer)
File "/var/lang/lib/python3.6/ssl.py", line 874, in read
return self._sslobj.read(len, buffer)
File "/var/lang/lib/python3.6/ssl.py", line 631, in read
v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
status = self.run(options, args)
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 318, in run
resolver.resolve(requirement_set)
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 102, in resolve
self._resolve_one(requirement_set, req)
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
abstract_dist = self._get_abstract_dist_for(req_to_install)
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
self.require_hashes
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 283, in prepare_linked_requirement
progress_bar=self.progress_bar
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 836, in unpack_url
progress_bar=progress_bar
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 673, in unpack_http_url
progress_bar)
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 897, in _download_http_url
_download_url(resp, link, content_file, hashes, progress_bar)
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 617, in _download_url
hashes.check_against_chunks(downloaded_chunks)
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/utils/hashes.py", line 48, in check_against_chunks
for chunk in chunks:
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 585, in written_chunks
for chunk in chunks:
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/utils/ui.py", line 159, in iter
for x in it:
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_internal/download.py", line 574, in resp_read
decode_content=False):
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 465, in stream
data = self.read(amt=amt, decode_content=decode_content)
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 430, in read
raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
File "/var/lang/lib/python3.6/contextlib.py", line 99, in __exit__
self.gen.throw(type, value, traceback)
File "/tmp/accretion/venv/lib/python3.6/site-packages/pip/_vendor/urllib3/response.py", line 349, in _error_catcher
raise ProtocolError('Connection broken: %r' % e, e)
pip._vendor.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
You are using pip version 18.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


01:59:42
Failed to execute command: ExecutionError Traceback (most recent call last): File "/var/task/accretion_workers/artifact_builder/zip_builder.py", line 136, in lambda_handler installed = build_requirements(build_dir=BUILD_DIR, venv_dir=VENV_DIR, requirements=requirements) File "/var/task/accretion_common/venv_magic/builder.py", line 80, in build_requirements _build_venv(venv_dir) File
Failed to execute command: ExecutionError
Traceback (most recent call last):
File "/var/task/accretion_workers/artifact_builder/zip_builder.py", line 136, in lambda_handler
installed = build_requirements(build_dir=BUILD_DIR, venv_dir=VENV_DIR, requirements=requirements)
File "/var/task/accretion_common/venv_magic/builder.py", line 80, in build_requirements
_build_venv(venv_dir)
File "/var/task/accretion_common/venv_magic/builder.py", line 38, in _build_venv
return _execute_in_venv(venv_dir=venv_dir, command="pip install --no-cache-dir --upgrade pip")
File "/var/task/accretion_common/venv_magic/builder.py", line 32, in _execute_in_venv
return _execute_command(f"source {venv_dir}/bin/activate; {command}; deactivate")
File "/var/task/accretion_common/venv_magic/builder.py", line 27, in _execute_command
raise ExecutionError("Failed to execute command")
accretion_common.exceptions.ExecutionError: Failed to execute command
```

**Comment by mattsb42** [comment]
closing project as discussed in #35
